openapi: 3.0.0
info:
  title: Todo App Todo Management API
  version: 1.0.0
  description: API for managing todo tasks in the multi-user todo application

paths:
  /todos:
    get:
      summary: Get user's todo tasks
      description: Retrieve all todo tasks for the authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully retrieved user's todo tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized - invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new todo task
      description: Create a new todo task for the authenticated user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
      responses:
        '201':
          description: Todo task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /todos/{id}:
    get:
      summary: Get a specific todo task
      description: Retrieve a specific todo task by ID for the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the todo task to retrieve
      responses:
        '200':
          description: Successfully retrieved the todo task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized - invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Todo task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a todo task
      description: Update an existing todo task for the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the todo task to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoRequest'
      responses:
        '200':
          description: Todo task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Todo task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a todo task
      description: Delete a specific todo task by ID for the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the todo task to delete
      responses:
        '204':
          description: Todo task deleted successfully
        '401':
          description: Unauthorized - invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Todo task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /todos/{id}/toggle-complete:
    patch:
      summary: Toggle completion status of a todo task
      description: Toggle the completion status of a specific todo task for the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the todo task to toggle
      responses:
        '200':
          description: Todo task completion status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized - invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Todo task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          maxLength: 200
          example: "Buy groceries"
        description:
          type: string
          maxLength: 1000
          example: "Need to buy milk, bread, and eggs"
        is_completed:
          type: boolean
          example: false
        user_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174001"
        created_at:
          type: string
          format: date-time
          example: "2023-10-20T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2023-10-20T10:00:00Z"
        due_date:
          type: string
          format: date-time
          nullable: true
          example: "2023-10-25T18:00:00Z"
      required:
        - id
        - title
        - is_completed
        - user_id
        - created_at
        - updated_at
    
    CreateTodoRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
          example: "Buy groceries"
        description:
          type: string
          maxLength: 1000
          example: "Need to buy milk, bread, and eggs"
        due_date:
          type: string
          format: date-time
          nullable: true
          example: "2023-10-25T18:00:00Z"
      required:
        - title
    
    UpdateTodoRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
          example: "Buy groceries"
        description:
          type: string
          maxLength: 1000
          example: "Need to buy milk, bread, and eggs"
        due_date:
          type: string
          format: date-time
          nullable: true
          example: "2023-10-25T18:00:00Z"
    
    Error:
      type: object
      properties:
        detail:
          type: string
          example: "Todo task not found"